name: ClaudeCodeMenu
options:
  bundleIdPrefix: com.anthropic
  deploymentTarget:
    macOS: "13.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

settings:
  base:
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"

targets:
  ClaudeCodeMenu:
    type: application
    platform: macOS
    sources:
      - path: ClaudeCodeMenu
        excludes:
          - "Resources/**"
      - path: ClaudeCodeMenu/Resources/open-claude.scpt
        buildPhase: resources
      - path: ClaudeCodeMenu/Resources/resume-claude.scpt
        buildPhase: resources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.anthropic.ClaudeCodeMenu
        INFOPLIST_FILE: ClaudeCodeMenu/Info.plist
        CODE_SIGN_ENTITLEMENTS: ClaudeCodeMenu/ClaudeCodeMenu.entitlements
        ENABLE_APP_SANDBOX: NO
        PRODUCT_NAME: Claude Code Menu
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        COMBINE_HIDPI_IMAGES: YES
        SWIFT_VERSION: "5.9"
    dependencies:
      - target: FinderExtension

  FinderExtension:
    type: app-extension
    platform: macOS
    sources:
      - path: FinderExtension
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.anthropic.ClaudeCodeMenu.FinderExtension
        INFOPLIST_FILE: FinderExtension/Info.plist
        CODE_SIGN_ENTITLEMENTS: FinderExtension/FinderExtension.entitlements
        ENABLE_APP_SANDBOX: YES
        PRODUCT_NAME: FinderExtension
        COMBINE_HIDPI_IMAGES: YES
        SWIFT_VERSION: "5.9"
